// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: academic_sessions.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createAcademicSession = `-- name: CreateAcademicSession :one
INSERT INTO academic_sessions (
    tenant_id, name, start_date, end_date, is_current
)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, tenant_id, name, start_date, end_date, is_current, created_at, updated_at
`

type CreateAcademicSessionParams struct {
	TenantID  uuid.UUID `json:"tenant_id"`
	Name      string    `json:"name"`
	StartDate time.Time `json:"start_date"`
	EndDate   time.Time `json:"end_date"`
	IsCurrent bool      `json:"is_current"`
}

func (q *Queries) CreateAcademicSession(ctx context.Context, arg CreateAcademicSessionParams) (AcademicSession, error) {
	row := q.db.QueryRow(ctx, createAcademicSession,
		arg.TenantID,
		arg.Name,
		arg.StartDate,
		arg.EndDate,
		arg.IsCurrent,
	)
	var i AcademicSession
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.StartDate,
		&i.EndDate,
		&i.IsCurrent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAcademicSessionById = `-- name: GetAcademicSessionById :one
SELECT id, tenant_id, name, start_date, end_date, is_current, created_at, updated_at FROM academic_sessions
WHERE id = $1 AND tenant_id = $2
`

type GetAcademicSessionByIdParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetAcademicSessionById(ctx context.Context, arg GetAcademicSessionByIdParams) (AcademicSession, error) {
	row := q.db.QueryRow(ctx, getAcademicSessionById, arg.ID, arg.TenantID)
	var i AcademicSession
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.StartDate,
		&i.EndDate,
		&i.IsCurrent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCurrentAcademicSession = `-- name: GetCurrentAcademicSession :one
SELECT id, tenant_id, name, start_date, end_date, is_current, created_at, updated_at FROM academic_sessions
WHERE tenant_id = $1 AND is_current = true
`

func (q *Queries) GetCurrentAcademicSession(ctx context.Context, tenantID uuid.UUID) (AcademicSession, error) {
	row := q.db.QueryRow(ctx, getCurrentAcademicSession, tenantID)
	var i AcademicSession
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.StartDate,
		&i.EndDate,
		&i.IsCurrent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAcademicSessions = `-- name: ListAcademicSessions :many
SELECT id, tenant_id, name, start_date, end_date, is_current, created_at, updated_at FROM academic_sessions
WHERE tenant_id = $1
ORDER BY start_date DESC
`

func (q *Queries) ListAcademicSessions(ctx context.Context, tenantID uuid.UUID) ([]AcademicSession, error) {
	rows, err := q.db.Query(ctx, listAcademicSessions, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AcademicSession{}
	for rows.Next() {
		var i AcademicSession
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.StartDate,
			&i.EndDate,
			&i.IsCurrent,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCurrentAcademicSession = `-- name: SetCurrentAcademicSession :exec
UPDATE academic_sessions
SET is_current = false, updated_at = NOW()
WHERE tenant_id = $1 AND is_current = true
`

func (q *Queries) SetCurrentAcademicSession(ctx context.Context, tenantID uuid.UUID) error {
	_, err := q.db.Exec(ctx, setCurrentAcademicSession, tenantID)
	return err
}

const updateAcademicSession = `-- name: UpdateAcademicSession :one
UPDATE academic_sessions
SET 
    name = COALESCE($3, name),
    start_date = COALESCE($4, start_date),
    end_date = COALESCE($5, end_date),
    is_current = COALESCE($6, is_current),
    updated_at = NOW()
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, name, start_date, end_date, is_current, created_at, updated_at
`

type UpdateAcademicSessionParams struct {
	ID        uuid.UUID `json:"id"`
	TenantID  uuid.UUID `json:"tenant_id"`
	Name      string    `json:"name"`
	StartDate time.Time `json:"start_date"`
	EndDate   time.Time `json:"end_date"`
	IsCurrent bool      `json:"is_current"`
}

func (q *Queries) UpdateAcademicSession(ctx context.Context, arg UpdateAcademicSessionParams) (AcademicSession, error) {
	row := q.db.QueryRow(ctx, updateAcademicSession,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.StartDate,
		arg.EndDate,
		arg.IsCurrent,
	)
	var i AcademicSession
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.StartDate,
		&i.EndDate,
		&i.IsCurrent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
