// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admissions.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAdmission = `-- name: CreateAdmission :one
INSERT INTO admissions (
    tenant_id, academic_session_id,
    first_name, last_name, middle_name,
    gender, date_of_birth,
    preferred_class_id,
    parent_first_name, parent_last_name,
    parent_phone_number, parent_email,
    parent_relationship
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING id, tenant_id, academic_session_id, first_name, last_name, middle_name, gender, date_of_birth, preferred_class_id, status, admission_number, student_id, reviewed_by, reviewed_at, rejection_reason, parent_first_name, parent_last_name, parent_phone_number, parent_email, parent_relationship, created_at, updated_at
`

type CreateAdmissionParams struct {
	TenantID           pgtype.UUID `json:"tenant_id"`
	AcademicSessionID  pgtype.UUID `json:"academic_session_id"`
	FirstName          string      `json:"first_name"`
	LastName           string      `json:"last_name"`
	MiddleName         *string     `json:"middle_name"`
	Gender             string      `json:"gender"`
	DateOfBirth        pgtype.Date `json:"date_of_birth"`
	PreferredClassID   pgtype.UUID `json:"preferred_class_id"`
	ParentFirstName    string      `json:"parent_first_name"`
	ParentLastName     string      `json:"parent_last_name"`
	ParentPhoneNumber  string      `json:"parent_phone_number"`
	ParentEmail        string      `json:"parent_email"`
	ParentRelationship string      `json:"parent_relationship"`
}

func (q *Queries) CreateAdmission(ctx context.Context, arg CreateAdmissionParams) (Admission, error) {
	row := q.db.QueryRow(ctx, createAdmission,
		arg.TenantID,
		arg.AcademicSessionID,
		arg.FirstName,
		arg.LastName,
		arg.MiddleName,
		arg.Gender,
		arg.DateOfBirth,
		arg.PreferredClassID,
		arg.ParentFirstName,
		arg.ParentLastName,
		arg.ParentPhoneNumber,
		arg.ParentEmail,
		arg.ParentRelationship,
	)
	var i Admission
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AcademicSessionID,
		&i.FirstName,
		&i.LastName,
		&i.MiddleName,
		&i.Gender,
		&i.DateOfBirth,
		&i.PreferredClassID,
		&i.Status,
		&i.AdmissionNumber,
		&i.StudentID,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.RejectionReason,
		&i.ParentFirstName,
		&i.ParentLastName,
		&i.ParentPhoneNumber,
		&i.ParentEmail,
		&i.ParentRelationship,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAdmissionById = `-- name: GetAdmissionById :one
SELECT id, tenant_id, academic_session_id, first_name, last_name, middle_name, gender, date_of_birth, preferred_class_id, status, admission_number, student_id, reviewed_by, reviewed_at, rejection_reason, parent_first_name, parent_last_name, parent_phone_number, parent_email, parent_relationship, created_at, updated_at FROM admissions
WHERE id = $1 AND tenant_id = $2
`

type GetAdmissionByIdParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) GetAdmissionById(ctx context.Context, arg GetAdmissionByIdParams) (Admission, error) {
	row := q.db.QueryRow(ctx, getAdmissionById, arg.ID, arg.TenantID)
	var i Admission
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AcademicSessionID,
		&i.FirstName,
		&i.LastName,
		&i.MiddleName,
		&i.Gender,
		&i.DateOfBirth,
		&i.PreferredClassID,
		&i.Status,
		&i.AdmissionNumber,
		&i.StudentID,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.RejectionReason,
		&i.ParentFirstName,
		&i.ParentLastName,
		&i.ParentPhoneNumber,
		&i.ParentEmail,
		&i.ParentRelationship,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAdmissions = `-- name: ListAdmissions :many
SELECT id, tenant_id, academic_session_id, first_name, last_name, middle_name, gender, date_of_birth, preferred_class_id, status, admission_number, student_id, reviewed_by, reviewed_at, rejection_reason, parent_first_name, parent_last_name, parent_phone_number, parent_email, parent_relationship, created_at, updated_at FROM admissions
WHERE tenant_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListAdmissions(ctx context.Context, tenantID pgtype.UUID) ([]Admission, error) {
	rows, err := q.db.Query(ctx, listAdmissions, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Admission{}
	for rows.Next() {
		var i Admission
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.AcademicSessionID,
			&i.FirstName,
			&i.LastName,
			&i.MiddleName,
			&i.Gender,
			&i.DateOfBirth,
			&i.PreferredClassID,
			&i.Status,
			&i.AdmissionNumber,
			&i.StudentID,
			&i.ReviewedBy,
			&i.ReviewedAt,
			&i.RejectionReason,
			&i.ParentFirstName,
			&i.ParentLastName,
			&i.ParentPhoneNumber,
			&i.ParentEmail,
			&i.ParentRelationship,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdmissionsByStatus = `-- name: ListAdmissionsByStatus :many
SELECT id, tenant_id, academic_session_id, first_name, last_name, middle_name, gender, date_of_birth, preferred_class_id, status, admission_number, student_id, reviewed_by, reviewed_at, rejection_reason, parent_first_name, parent_last_name, parent_phone_number, parent_email, parent_relationship, created_at, updated_at FROM admissions
WHERE tenant_id = $1 AND status = $2
ORDER BY created_at DESC
`

type ListAdmissionsByStatusParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Status   string      `json:"status"`
}

func (q *Queries) ListAdmissionsByStatus(ctx context.Context, arg ListAdmissionsByStatusParams) ([]Admission, error) {
	rows, err := q.db.Query(ctx, listAdmissionsByStatus, arg.TenantID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Admission{}
	for rows.Next() {
		var i Admission
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.AcademicSessionID,
			&i.FirstName,
			&i.LastName,
			&i.MiddleName,
			&i.Gender,
			&i.DateOfBirth,
			&i.PreferredClassID,
			&i.Status,
			&i.AdmissionNumber,
			&i.StudentID,
			&i.ReviewedBy,
			&i.ReviewedAt,
			&i.RejectionReason,
			&i.ParentFirstName,
			&i.ParentLastName,
			&i.ParentPhoneNumber,
			&i.ParentEmail,
			&i.ParentRelationship,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAdmissionStatus = `-- name: UpdateAdmissionStatus :one
UPDATE admissions
SET
    status = $3,
    reviewed_by = $4,
    reviewed_at = NOW(),
    rejection_reason = $5,
    admission_number = $6,
    student_id = $7,
    updated_at = NOW()
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, academic_session_id, first_name, last_name, middle_name, gender, date_of_birth, preferred_class_id, status, admission_number, student_id, reviewed_by, reviewed_at, rejection_reason, parent_first_name, parent_last_name, parent_phone_number, parent_email, parent_relationship, created_at, updated_at
`

type UpdateAdmissionStatusParams struct {
	ID              pgtype.UUID `json:"id"`
	TenantID        pgtype.UUID `json:"tenant_id"`
	Status          string      `json:"status"`
	ReviewedBy      pgtype.UUID `json:"reviewed_by"`
	RejectionReason *string     `json:"rejection_reason"`
	AdmissionNumber *string     `json:"admission_number"`
	StudentID       pgtype.UUID `json:"student_id"`
}

func (q *Queries) UpdateAdmissionStatus(ctx context.Context, arg UpdateAdmissionStatusParams) (Admission, error) {
	row := q.db.QueryRow(ctx, updateAdmissionStatus,
		arg.ID,
		arg.TenantID,
		arg.Status,
		arg.ReviewedBy,
		arg.RejectionReason,
		arg.AdmissionNumber,
		arg.StudentID,
	)
	var i Admission
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AcademicSessionID,
		&i.FirstName,
		&i.LastName,
		&i.MiddleName,
		&i.Gender,
		&i.DateOfBirth,
		&i.PreferredClassID,
		&i.Status,
		&i.AdmissionNumber,
		&i.StudentID,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.RejectionReason,
		&i.ParentFirstName,
		&i.ParentLastName,
		&i.ParentPhoneNumber,
		&i.ParentEmail,
		&i.ParentRelationship,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
