// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: assessment_type.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const createAssessmentType = `-- name: CreateAssessmentType :one
INSERT INTO assessment_types (tenant_id, name, max_score, weight, is_exam)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, tenant_id, name, max_score, weight, is_exam, created_at, updated_at
`

type CreateAssessmentTypeParams struct {
	TenantID uuid.UUID        `json:"tenant_id"`
	Name     string           `json:"name"`
	MaxScore decimal.Decimal  `json:"max_score"`
	Weight   *decimal.Decimal `json:"weight"`
	IsExam   bool             `json:"is_exam"`
}

func (q *Queries) CreateAssessmentType(ctx context.Context, arg CreateAssessmentTypeParams) (AssessmentType, error) {
	row := q.db.QueryRow(ctx, createAssessmentType,
		arg.TenantID,
		arg.Name,
		arg.MaxScore,
		arg.Weight,
		arg.IsExam,
	)
	var i AssessmentType
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.MaxScore,
		&i.Weight,
		&i.IsExam,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAssessmentTypeByID = `-- name: GetAssessmentTypeByID :one
SELECT id, tenant_id, name, max_score, weight, is_exam, created_at, updated_at FROM assessment_types
WHERE id = $1 AND tenant_id = $2
`

type GetAssessmentTypeByIDParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetAssessmentTypeByID(ctx context.Context, arg GetAssessmentTypeByIDParams) (AssessmentType, error) {
	row := q.db.QueryRow(ctx, getAssessmentTypeByID, arg.ID, arg.TenantID)
	var i AssessmentType
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.MaxScore,
		&i.Weight,
		&i.IsExam,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAssessmentTypes = `-- name: ListAssessmentTypes :many
SELECT id, tenant_id, name, max_score, weight, is_exam, created_at, updated_at FROM assessment_types
WHERE tenant_id = $1
ORDER BY name
`

func (q *Queries) ListAssessmentTypes(ctx context.Context, tenantID uuid.UUID) ([]AssessmentType, error) {
	rows, err := q.db.Query(ctx, listAssessmentTypes, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AssessmentType{}
	for rows.Next() {
		var i AssessmentType
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.MaxScore,
			&i.Weight,
			&i.IsExam,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
