// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const createAuditLog = `-- name: CreateAuditLog :one
INSERT INTO audit_logs (
    tenant_id, user_id, action, resource_type, resource_id,
    metadata, ip_address, user_agent, request_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
) RETURNING id, tenant_id, user_id, action, resource_type, resource_id, metadata, ip_address, user_agent, request_id, created_at
`

type CreateAuditLogParams struct {
	TenantID     *uuid.UUID `json:"tenant_id"`
	UserID       *uuid.UUID `json:"user_id"`
	Action       string     `json:"action"`
	ResourceType *string    `json:"resource_type"`
	ResourceID   *uuid.UUID `json:"resource_id"`
	Metadata     []byte     `json:"metadata"`
	IpAddress    *string    `json:"ip_address"`
	UserAgent    *string    `json:"user_agent"`
	RequestID    *string    `json:"request_id"`
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, createAuditLog,
		arg.TenantID,
		arg.UserID,
		arg.Action,
		arg.ResourceType,
		arg.ResourceID,
		arg.Metadata,
		arg.IpAddress,
		arg.UserAgent,
		arg.RequestID,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.Action,
		&i.ResourceType,
		&i.ResourceID,
		&i.Metadata,
		&i.IpAddress,
		&i.UserAgent,
		&i.RequestID,
		&i.CreatedAt,
	)
	return i, err
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT id, tenant_id, user_id, action, resource_type, resource_id, metadata, ip_address, user_agent, request_id, created_at FROM audit_logs
WHERE tenant_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListAuditLogsParams struct {
	TenantID *uuid.UUID `json:"tenant_id"`
	Limit    int32      `json:"limit"`
	Offset   int32      `json:"offset"`
}

func (q *Queries) ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogs, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.Metadata,
			&i.IpAddress,
			&i.UserAgent,
			&i.RequestID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
