// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: classes.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createClass = `-- name: CreateClass :one
INSERT INTO classes (
    tenant_id, name , level_order
)
VALUES ($1, $2, $3)
RETURNING id, tenant_id, name, level_order, created_at, updated_at
`

type CreateClassParams struct {
	TenantID   pgtype.UUID `json:"tenant_id"`
	Name       string      `json:"name"`
	LevelOrder int32       `json:"level_order"`
}

func (q *Queries) CreateClass(ctx context.Context, arg CreateClassParams) (Class, error) {
	row := q.db.QueryRow(ctx, createClass, arg.TenantID, arg.Name, arg.LevelOrder)
	var i Class
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.LevelOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createClassArm = `-- name: CreateClassArm :one
INSERT INTO class_arms (
    tenant_id, class_id, name
)
VALUES ($1, $2, $3)
RETURNING id, tenant_id, class_id, name, created_at, updated_at
`

type CreateClassArmParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ClassID  pgtype.UUID `json:"class_id"`
	Name     string      `json:"name"`
}

func (q *Queries) CreateClassArm(ctx context.Context, arg CreateClassArmParams) (ClassArm, error) {
	row := q.db.QueryRow(ctx, createClassArm, arg.TenantID, arg.ClassID, arg.Name)
	var i ClassArm
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ClassID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getClassByID = `-- name: GetClassByID :one
SELECT id, tenant_id, name, level_order, created_at, updated_at FROM classes
WHERE id = $1 AND tenant_id = $2
`

type GetClassByIDParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) GetClassByID(ctx context.Context, arg GetClassByIDParams) (Class, error) {
	row := q.db.QueryRow(ctx, getClassByID, arg.ID, arg.TenantID)
	var i Class
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.LevelOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllClassArms = `-- name: ListAllClassArms :many
SELECT ca.id, ca.tenant_id, ca.class_id, ca.name, ca.created_at, ca.updated_at , c.name as class_name
FROM class_arms ca
JOIN classes c ON c.id = ca.class_id
WHERE ca.tenant_id = $1
ORDER by c.level_order, ca.name
`

type ListAllClassArmsRow struct {
	ID        pgtype.UUID        `json:"id"`
	TenantID  pgtype.UUID        `json:"tenant_id"`
	ClassID   pgtype.UUID        `json:"class_id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	ClassName string             `json:"class_name"`
}

func (q *Queries) ListAllClassArms(ctx context.Context, tenantID pgtype.UUID) ([]ListAllClassArmsRow, error) {
	rows, err := q.db.Query(ctx, listAllClassArms, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllClassArmsRow{}
	for rows.Next() {
		var i ListAllClassArmsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ClassID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClassName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClassArms = `-- name: ListClassArms :many
SELECT id, tenant_id, class_id, name, created_at, updated_at FROM class_arms
WHERE tenant_id = $1 AND class_id = $2
ORDER BY name
`

type ListClassArmsParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ClassID  pgtype.UUID `json:"class_id"`
}

func (q *Queries) ListClassArms(ctx context.Context, arg ListClassArmsParams) ([]ClassArm, error) {
	rows, err := q.db.Query(ctx, listClassArms, arg.TenantID, arg.ClassID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClassArm{}
	for rows.Next() {
		var i ClassArm
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ClassID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClasses = `-- name: ListClasses :many
SELECT id, tenant_id, name, level_order, created_at, updated_at FROM classes
WHERE tenant_id = $1
ORDER BY level_order, name
`

func (q *Queries) ListClasses(ctx context.Context, tenantID pgtype.UUID) ([]Class, error) {
	rows, err := q.db.Query(ctx, listClasses, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Class{}
	for rows.Next() {
		var i Class
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.LevelOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
