// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: fees.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createFeeStructure = `-- name: CreateFeeStructure :one
INSERT INTO fee_structures (
    tenant_id, fee_type_id, academic_session_id,
    class_id, amount_kobo, due_date
)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, tenant_id, fee_type_id, academic_session_id, class_id, amount_kobo, due_date, created_at, updated_at
`

type CreateFeeStructureParams struct {
	TenantID          uuid.UUID  `json:"tenant_id"`
	FeeTypeID         uuid.UUID  `json:"fee_type_id"`
	AcademicSessionID uuid.UUID  `json:"academic_session_id"`
	ClassID           *uuid.UUID `json:"class_id"`
	AmountKobo        int64      `json:"amount_kobo"`
	DueDate           *time.Time `json:"due_date"`
}

func (q *Queries) CreateFeeStructure(ctx context.Context, arg CreateFeeStructureParams) (FeeStructure, error) {
	row := q.db.QueryRow(ctx, createFeeStructure,
		arg.TenantID,
		arg.FeeTypeID,
		arg.AcademicSessionID,
		arg.ClassID,
		arg.AmountKobo,
		arg.DueDate,
	)
	var i FeeStructure
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.FeeTypeID,
		&i.AcademicSessionID,
		&i.ClassID,
		&i.AmountKobo,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createFeeType = `-- name: CreateFeeType :one
INSERT INTO fee_types(
    tenant_id, name, description,
    is_optional
)
VALUES ($1, $2, $3, $4)
RETURNING id, tenant_id, name, description, is_optional, created_at, updated_at
`

type CreateFeeTypeParams struct {
	TenantID    uuid.UUID `json:"tenant_id"`
	Name        string    `json:"name"`
	Description *string   `json:"description"`
	IsOptional  bool      `json:"is_optional"`
}

func (q *Queries) CreateFeeType(ctx context.Context, arg CreateFeeTypeParams) (FeeType, error) {
	row := q.db.QueryRow(ctx, createFeeType,
		arg.TenantID,
		arg.Name,
		arg.Description,
		arg.IsOptional,
	)
	var i FeeType
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.IsOptional,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFeeStructureById = `-- name: GetFeeStructureById :one
SELECT id, tenant_id, fee_type_id, academic_session_id, class_id, amount_kobo, due_date, created_at, updated_at FROM fee_structures
WHERE id = $1 AND tenant_id = $2
`

type GetFeeStructureByIdParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetFeeStructureById(ctx context.Context, arg GetFeeStructureByIdParams) (FeeStructure, error) {
	row := q.db.QueryRow(ctx, getFeeStructureById, arg.ID, arg.TenantID)
	var i FeeStructure
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.FeeTypeID,
		&i.AcademicSessionID,
		&i.ClassID,
		&i.AmountKobo,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listFeeStructures = `-- name: ListFeeStructures :many
SELECT fs.id, fs.tenant_id, fs.fee_type_id, fs.academic_session_id, fs.class_id, fs.amount_kobo, fs.due_date, fs.created_at, fs.updated_at, ft.name AS fee_type_name
FROM fee_structures fs
INNER JOIN fee_types ft ON ft.id = fs.fee_type_id
WHERE fs.tenant_id = $1
`

type ListFeeStructuresRow struct {
	ID                uuid.UUID          `json:"id"`
	TenantID          uuid.UUID          `json:"tenant_id"`
	FeeTypeID         uuid.UUID          `json:"fee_type_id"`
	AcademicSessionID uuid.UUID          `json:"academic_session_id"`
	ClassID           *uuid.UUID         `json:"class_id"`
	AmountKobo        int64              `json:"amount_kobo"`
	DueDate           *time.Time         `json:"due_date"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	FeeTypeName       string             `json:"fee_type_name"`
}

func (q *Queries) ListFeeStructures(ctx context.Context, tenantID uuid.UUID) ([]ListFeeStructuresRow, error) {
	rows, err := q.db.Query(ctx, listFeeStructures, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFeeStructuresRow{}
	for rows.Next() {
		var i ListFeeStructuresRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.FeeTypeID,
			&i.AcademicSessionID,
			&i.ClassID,
			&i.AmountKobo,
			&i.DueDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FeeTypeName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFeeStructuresBySession = `-- name: ListFeeStructuresBySession :many
SELECT fs.id, fs.tenant_id, fs.fee_type_id, fs.academic_session_id, fs.class_id, fs.amount_kobo, fs.due_date, fs.created_at, fs.updated_at, ft.name AS fee_type_name
FROM fee_structures fs
JOIN fee_types ft ON ft.id = fs.fee_type_id
WHERE fs.tenant_id = $1 AND fs.academic_session_id = $2
ORDER BY ft.name
`

type ListFeeStructuresBySessionParams struct {
	TenantID          uuid.UUID `json:"tenant_id"`
	AcademicSessionID uuid.UUID `json:"academic_session_id"`
}

type ListFeeStructuresBySessionRow struct {
	ID                uuid.UUID          `json:"id"`
	TenantID          uuid.UUID          `json:"tenant_id"`
	FeeTypeID         uuid.UUID          `json:"fee_type_id"`
	AcademicSessionID uuid.UUID          `json:"academic_session_id"`
	ClassID           *uuid.UUID         `json:"class_id"`
	AmountKobo        int64              `json:"amount_kobo"`
	DueDate           *time.Time         `json:"due_date"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	FeeTypeName       string             `json:"fee_type_name"`
}

func (q *Queries) ListFeeStructuresBySession(ctx context.Context, arg ListFeeStructuresBySessionParams) ([]ListFeeStructuresBySessionRow, error) {
	rows, err := q.db.Query(ctx, listFeeStructuresBySession, arg.TenantID, arg.AcademicSessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFeeStructuresBySessionRow{}
	for rows.Next() {
		var i ListFeeStructuresBySessionRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.FeeTypeID,
			&i.AcademicSessionID,
			&i.ClassID,
			&i.AmountKobo,
			&i.DueDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FeeTypeName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFeeTypes = `-- name: ListFeeTypes :many
SELECT id, tenant_id, name, description, is_optional, created_at, updated_at FROM fee_types
WHERE tenant_id = $1
ORDER BY name
`

func (q *Queries) ListFeeTypes(ctx context.Context, tenantID uuid.UUID) ([]FeeType, error) {
	rows, err := q.db.Query(ctx, listFeeTypes, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FeeType{}
	for rows.Next() {
		var i FeeType
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Description,
			&i.IsOptional,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
