// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: fees.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createFeeStructure = `-- name: CreateFeeStructure :one
INSERT INTO fee_structures (
    tenant_id, fee_type_id, academic_session_id,
    class_id, amount_kobo, due_date
)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, tenant_id, fee_type_id, academic_session_id, class_id, amount_kobo, due_date, created_at, updated_at
`

type CreateFeeStructureParams struct {
	TenantID          uuid.UUID  `json:"tenant_id"`
	FeeTypeID         uuid.UUID  `json:"fee_type_id"`
	AcademicSessionID uuid.UUID  `json:"academic_session_id"`
	ClassID           *uuid.UUID `json:"class_id"`
	AmountKobo        int64      `json:"amount_kobo"`
	DueDate           *time.Time `json:"due_date"`
}

func (q *Queries) CreateFeeStructure(ctx context.Context, arg CreateFeeStructureParams) (FeeStructure, error) {
	row := q.db.QueryRow(ctx, createFeeStructure,
		arg.TenantID,
		arg.FeeTypeID,
		arg.AcademicSessionID,
		arg.ClassID,
		arg.AmountKobo,
		arg.DueDate,
	)
	var i FeeStructure
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.FeeTypeID,
		&i.AcademicSessionID,
		&i.ClassID,
		&i.AmountKobo,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createFeeType = `-- name: CreateFeeType :one
INSERT INTO fee_types(
    tenant_id, name, description,
    is_optional
)
VALUES ($1, $2, $3, $4)
RETURNING id, tenant_id, name, description, is_optional, created_at, updated_at
`

type CreateFeeTypeParams struct {
	TenantID    uuid.UUID `json:"tenant_id"`
	Name        string    `json:"name"`
	Description *string   `json:"description"`
	IsOptional  bool      `json:"is_optional"`
}

func (q *Queries) CreateFeeType(ctx context.Context, arg CreateFeeTypeParams) (FeeType, error) {
	row := q.db.QueryRow(ctx, createFeeType,
		arg.TenantID,
		arg.Name,
		arg.Description,
		arg.IsOptional,
	)
	var i FeeType
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.IsOptional,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (
    tenant_id, student_id, amount_kobo,
    payment_method, reference, received_by, notes
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, tenant_id, student_id, amount_kobo, payment_method, reference, received_by, paid_at, notes, created_at
`

type CreatePaymentParams struct {
	TenantID      uuid.UUID  `json:"tenant_id"`
	StudentID     uuid.UUID  `json:"student_id"`
	AmountKobo    int64      `json:"amount_kobo"`
	PaymentMethod string     `json:"payment_method"`
	Reference     *string    `json:"reference"`
	ReceivedBy    *uuid.UUID `json:"received_by"`
	Notes         *string    `json:"notes"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.TenantID,
		arg.StudentID,
		arg.AmountKobo,
		arg.PaymentMethod,
		arg.Reference,
		arg.ReceivedBy,
		arg.Notes,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.StudentID,
		&i.AmountKobo,
		&i.PaymentMethod,
		&i.Reference,
		&i.ReceivedBy,
		&i.PaidAt,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const createPaymentAllocation = `-- name: CreatePaymentAllocation :one
INSERT INTO payment_allocations(
    payment_id, student_fee_id, amount_kobo
)
VALUES ($1, $2, $3)
RETURNING id, payment_id, student_fee_id, amount_kobo
`

type CreatePaymentAllocationParams struct {
	PaymentID    uuid.UUID `json:"payment_id"`
	StudentFeeID uuid.UUID `json:"student_fee_id"`
	AmountKobo   int64     `json:"amount_kobo"`
}

func (q *Queries) CreatePaymentAllocation(ctx context.Context, arg CreatePaymentAllocationParams) (PaymentAllocation, error) {
	row := q.db.QueryRow(ctx, createPaymentAllocation, arg.PaymentID, arg.StudentFeeID, arg.AmountKobo)
	var i PaymentAllocation
	err := row.Scan(
		&i.ID,
		&i.PaymentID,
		&i.StudentFeeID,
		&i.AmountKobo,
	)
	return i, err
}

const createStudentFee = `-- name: CreateStudentFee :one
INSERT INTO student_fees (
    tenant_id, student_id, fee_structure_id,
    amount_kobo, due_date
)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT ON CONSTRAINT student_fees_unique DO NOTHING
RETURNING id, tenant_id, student_id, fee_structure_id, amount_kobo, amount_paid_kobo, status, due_date, created_at, updated_at
`

type CreateStudentFeeParams struct {
	TenantID       uuid.UUID  `json:"tenant_id"`
	StudentID      uuid.UUID  `json:"student_id"`
	FeeStructureID uuid.UUID  `json:"fee_structure_id"`
	AmountKobo     int64      `json:"amount_kobo"`
	DueDate        *time.Time `json:"due_date"`
}

func (q *Queries) CreateStudentFee(ctx context.Context, arg CreateStudentFeeParams) (StudentFee, error) {
	row := q.db.QueryRow(ctx, createStudentFee,
		arg.TenantID,
		arg.StudentID,
		arg.FeeStructureID,
		arg.AmountKobo,
		arg.DueDate,
	)
	var i StudentFee
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.StudentID,
		&i.FeeStructureID,
		&i.AmountKobo,
		&i.AmountPaidKobo,
		&i.Status,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFeeStructureById = `-- name: GetFeeStructureById :one
SELECT id, tenant_id, fee_type_id, academic_session_id, class_id, amount_kobo, due_date, created_at, updated_at FROM fee_structures
WHERE id = $1 AND tenant_id = $2
`

type GetFeeStructureByIdParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetFeeStructureById(ctx context.Context, arg GetFeeStructureByIdParams) (FeeStructure, error) {
	row := q.db.QueryRow(ctx, getFeeStructureById, arg.ID, arg.TenantID)
	var i FeeStructure
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.FeeTypeID,
		&i.AcademicSessionID,
		&i.ClassID,
		&i.AmountKobo,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStudentFeeByID = `-- name: GetStudentFeeByID :one
SELECT id, tenant_id, student_id, fee_structure_id, amount_kobo, amount_paid_kobo, status, due_date, created_at, updated_at FROM student_fees
WHERE id = $1 AND tenant_id = $2
`

type GetStudentFeeByIDParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetStudentFeeByID(ctx context.Context, arg GetStudentFeeByIDParams) (StudentFee, error) {
	row := q.db.QueryRow(ctx, getStudentFeeByID, arg.ID, arg.TenantID)
	var i StudentFee
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.StudentID,
		&i.FeeStructureID,
		&i.AmountKobo,
		&i.AmountPaidKobo,
		&i.Status,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStudentFeeSummary = `-- name: GetStudentFeeSummary :one
SELECT 
    COALESCE(SUM(amount_kobo), 0) AS total_amount,
    COALESCE(SUM(amount_paid_kobo), 0) AS total_paid,
    COALESCE(SUM(amount_kobo - amount_paid_kobo), 0) AS balance
FROM student_fees
WHERE tenant_id = $1 AND student_id = $2
`

type GetStudentFeeSummaryParams struct {
	TenantID  uuid.UUID `json:"tenant_id"`
	StudentID uuid.UUID `json:"student_id"`
}

type GetStudentFeeSummaryRow struct {
	TotalAmount interface{} `json:"total_amount"`
	TotalPaid   interface{} `json:"total_paid"`
	Balance     interface{} `json:"balance"`
}

func (q *Queries) GetStudentFeeSummary(ctx context.Context, arg GetStudentFeeSummaryParams) (GetStudentFeeSummaryRow, error) {
	row := q.db.QueryRow(ctx, getStudentFeeSummary, arg.TenantID, arg.StudentID)
	var i GetStudentFeeSummaryRow
	err := row.Scan(&i.TotalAmount, &i.TotalPaid, &i.Balance)
	return i, err
}

const listFeeStructures = `-- name: ListFeeStructures :many
SELECT fs.id, fs.tenant_id, fs.fee_type_id, fs.academic_session_id, fs.class_id, fs.amount_kobo, fs.due_date, fs.created_at, fs.updated_at, ft.name AS fee_type_name
FROM fee_structures fs
INNER JOIN fee_types ft ON ft.id = fs.fee_type_id
WHERE fs.tenant_id = $1
`

type ListFeeStructuresRow struct {
	ID                uuid.UUID          `json:"id"`
	TenantID          uuid.UUID          `json:"tenant_id"`
	FeeTypeID         uuid.UUID          `json:"fee_type_id"`
	AcademicSessionID uuid.UUID          `json:"academic_session_id"`
	ClassID           *uuid.UUID         `json:"class_id"`
	AmountKobo        int64              `json:"amount_kobo"`
	DueDate           *time.Time         `json:"due_date"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	FeeTypeName       string             `json:"fee_type_name"`
}

func (q *Queries) ListFeeStructures(ctx context.Context, tenantID uuid.UUID) ([]ListFeeStructuresRow, error) {
	rows, err := q.db.Query(ctx, listFeeStructures, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFeeStructuresRow{}
	for rows.Next() {
		var i ListFeeStructuresRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.FeeTypeID,
			&i.AcademicSessionID,
			&i.ClassID,
			&i.AmountKobo,
			&i.DueDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FeeTypeName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFeeStructuresBySession = `-- name: ListFeeStructuresBySession :many
SELECT fs.id, fs.tenant_id, fs.fee_type_id, fs.academic_session_id, fs.class_id, fs.amount_kobo, fs.due_date, fs.created_at, fs.updated_at, ft.name AS fee_type_name
FROM fee_structures fs
JOIN fee_types ft ON ft.id = fs.fee_type_id
WHERE fs.tenant_id = $1 AND fs.academic_session_id = $2
ORDER BY ft.name
`

type ListFeeStructuresBySessionParams struct {
	TenantID          uuid.UUID `json:"tenant_id"`
	AcademicSessionID uuid.UUID `json:"academic_session_id"`
}

type ListFeeStructuresBySessionRow struct {
	ID                uuid.UUID          `json:"id"`
	TenantID          uuid.UUID          `json:"tenant_id"`
	FeeTypeID         uuid.UUID          `json:"fee_type_id"`
	AcademicSessionID uuid.UUID          `json:"academic_session_id"`
	ClassID           *uuid.UUID         `json:"class_id"`
	AmountKobo        int64              `json:"amount_kobo"`
	DueDate           *time.Time         `json:"due_date"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	FeeTypeName       string             `json:"fee_type_name"`
}

func (q *Queries) ListFeeStructuresBySession(ctx context.Context, arg ListFeeStructuresBySessionParams) ([]ListFeeStructuresBySessionRow, error) {
	rows, err := q.db.Query(ctx, listFeeStructuresBySession, arg.TenantID, arg.AcademicSessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFeeStructuresBySessionRow{}
	for rows.Next() {
		var i ListFeeStructuresBySessionRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.FeeTypeID,
			&i.AcademicSessionID,
			&i.ClassID,
			&i.AmountKobo,
			&i.DueDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FeeTypeName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFeeTypes = `-- name: ListFeeTypes :many
SELECT id, tenant_id, name, description, is_optional, created_at, updated_at FROM fee_types
WHERE tenant_id = $1
ORDER BY name
`

func (q *Queries) ListFeeTypes(ctx context.Context, tenantID uuid.UUID) ([]FeeType, error) {
	rows, err := q.db.Query(ctx, listFeeTypes, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FeeType{}
	for rows.Next() {
		var i FeeType
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Description,
			&i.IsOptional,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOutstandingFees = `-- name: ListOutstandingFees :many
SELECT
    sf.id, sf.tenant_id, sf.student_id, sf.fee_structure_id, sf.amount_kobo, sf.amount_paid_kobo, sf.status, sf.due_date, sf.created_at, sf.updated_at,
    s.admission_number,
    s.first_name,
    s.last_name,
    ft.name AS fee_type_name
FROM student_fees sf
JOIN students s ON s.id = sf.student_id
JOIN fee_structures fs ON fs.id = sf.fee_structure_id
JOIN fee_types ft ON ft.id = sf.fee_type_id
WHERE sf.tenant_id = $1 AND sf.status IN ('unpaid', 'partial')
ORDER BY s.last_name, s.first_name, ft.name
`

type ListOutstandingFeesRow struct {
	ID              uuid.UUID          `json:"id"`
	TenantID        uuid.UUID          `json:"tenant_id"`
	StudentID       uuid.UUID          `json:"student_id"`
	FeeStructureID  uuid.UUID          `json:"fee_structure_id"`
	AmountKobo      int64              `json:"amount_kobo"`
	AmountPaidKobo  int64              `json:"amount_paid_kobo"`
	Status          string             `json:"status"`
	DueDate         *time.Time         `json:"due_date"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	AdmissionNumber string             `json:"admission_number"`
	FirstName       string             `json:"first_name"`
	LastName        string             `json:"last_name"`
	FeeTypeName     string             `json:"fee_type_name"`
}

func (q *Queries) ListOutstandingFees(ctx context.Context, tenantID uuid.UUID) ([]ListOutstandingFeesRow, error) {
	rows, err := q.db.Query(ctx, listOutstandingFees, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOutstandingFeesRow{}
	for rows.Next() {
		var i ListOutstandingFeesRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.StudentID,
			&i.FeeStructureID,
			&i.AmountKobo,
			&i.AmountPaidKobo,
			&i.Status,
			&i.DueDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AdmissionNumber,
			&i.FirstName,
			&i.LastName,
			&i.FeeTypeName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOutstandingFeesByStudent = `-- name: ListOutstandingFeesByStudent :many
SELECT 
    sf.id, sf.tenant_id, sf.student_id, sf.fee_structure_id, sf.amount_kobo, sf.amount_paid_kobo, sf.status, sf.due_date, sf.created_at, sf.updated_at,
    ft.name AS fee_type_name
FROM student_fees sf
JOIN fee_structures fs ON fs.id = sf.fee_structure_id
JOIN fee_types ft ON ft.id = fs.fee_type_id
WHERE sf.tenant_id = $1 
  AND sf.student_id = $2
  AND sf.status IN ('unpaid', 'partial')
ORDER BY ft.name
`

type ListOutstandingFeesByStudentParams struct {
	TenantID  uuid.UUID `json:"tenant_id"`
	StudentID uuid.UUID `json:"student_id"`
}

type ListOutstandingFeesByStudentRow struct {
	ID             uuid.UUID          `json:"id"`
	TenantID       uuid.UUID          `json:"tenant_id"`
	StudentID      uuid.UUID          `json:"student_id"`
	FeeStructureID uuid.UUID          `json:"fee_structure_id"`
	AmountKobo     int64              `json:"amount_kobo"`
	AmountPaidKobo int64              `json:"amount_paid_kobo"`
	Status         string             `json:"status"`
	DueDate        *time.Time         `json:"due_date"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	FeeTypeName    string             `json:"fee_type_name"`
}

func (q *Queries) ListOutstandingFeesByStudent(ctx context.Context, arg ListOutstandingFeesByStudentParams) ([]ListOutstandingFeesByStudentRow, error) {
	rows, err := q.db.Query(ctx, listOutstandingFeesByStudent, arg.TenantID, arg.StudentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOutstandingFeesByStudentRow{}
	for rows.Next() {
		var i ListOutstandingFeesByStudentRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.StudentID,
			&i.FeeStructureID,
			&i.AmountKobo,
			&i.AmountPaidKobo,
			&i.Status,
			&i.DueDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FeeTypeName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentsByStudent = `-- name: ListPaymentsByStudent :many
SELECT id, tenant_id, student_id, amount_kobo, payment_method, reference, received_by, paid_at, notes, created_at FROM payments
WHERE tenant_id = $1 AND student_id = $2
ORDER BY paid_at DESC
`

type ListPaymentsByStudentParams struct {
	TenantID  uuid.UUID `json:"tenant_id"`
	StudentID uuid.UUID `json:"student_id"`
}

func (q *Queries) ListPaymentsByStudent(ctx context.Context, arg ListPaymentsByStudentParams) ([]Payment, error) {
	rows, err := q.db.Query(ctx, listPaymentsByStudent, arg.TenantID, arg.StudentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Payment{}
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.StudentID,
			&i.AmountKobo,
			&i.PaymentMethod,
			&i.Reference,
			&i.ReceivedBy,
			&i.PaidAt,
			&i.Notes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStudentFees = `-- name: ListStudentFees :many
SELECT sf.id, sf.tenant_id, sf.student_id, sf.fee_structure_id, sf.amount_kobo, sf.amount_paid_kobo, sf.status, sf.due_date, sf.created_at, sf.updated_at, ft.name AS fee_type_name
FROM student_fees sf
JOIN fee_structures fs ON fs.id = sf.fee_structure_id
JOIN fee_types ft ON ft.id = fs.fee_type_id
WHERE sf.tenant_id = $1 AND sf.student_id = $2
ORDER BY sf.created_at
`

type ListStudentFeesParams struct {
	TenantID  uuid.UUID `json:"tenant_id"`
	StudentID uuid.UUID `json:"student_id"`
}

type ListStudentFeesRow struct {
	ID             uuid.UUID          `json:"id"`
	TenantID       uuid.UUID          `json:"tenant_id"`
	StudentID      uuid.UUID          `json:"student_id"`
	FeeStructureID uuid.UUID          `json:"fee_structure_id"`
	AmountKobo     int64              `json:"amount_kobo"`
	AmountPaidKobo int64              `json:"amount_paid_kobo"`
	Status         string             `json:"status"`
	DueDate        *time.Time         `json:"due_date"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	FeeTypeName    string             `json:"fee_type_name"`
}

func (q *Queries) ListStudentFees(ctx context.Context, arg ListStudentFeesParams) ([]ListStudentFeesRow, error) {
	rows, err := q.db.Query(ctx, listStudentFees, arg.TenantID, arg.StudentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStudentFeesRow{}
	for rows.Next() {
		var i ListStudentFeesRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.StudentID,
			&i.FeeStructureID,
			&i.AmountKobo,
			&i.AmountPaidKobo,
			&i.Status,
			&i.DueDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FeeTypeName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnpaidStudentFees = `-- name: ListUnpaidStudentFees :many
SELECT id, tenant_id, student_id, fee_structure_id, amount_kobo, amount_paid_kobo, status, due_date, created_at, updated_at FROM student_fees
WHERE tenant_id = $1 AND student_id = $2 AND status != 'paid'
`

type ListUnpaidStudentFeesParams struct {
	TenantID  uuid.UUID `json:"tenant_id"`
	StudentID uuid.UUID `json:"student_id"`
}

func (q *Queries) ListUnpaidStudentFees(ctx context.Context, arg ListUnpaidStudentFeesParams) ([]StudentFee, error) {
	rows, err := q.db.Query(ctx, listUnpaidStudentFees, arg.TenantID, arg.StudentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StudentFee{}
	for rows.Next() {
		var i StudentFee
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.StudentID,
			&i.FeeStructureID,
			&i.AmountKobo,
			&i.AmountPaidKobo,
			&i.Status,
			&i.DueDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStudentFeePayment = `-- name: UpdateStudentFeePayment :one
UPDATE student_fees
SET 
    amount_paid_kobo = amount_paid_kobo + $3,
    status = CASE
        WHEN amount_paid_kobo + $3 >= amount_kobo THEN 'paid'
        WHEN amount_paid_kobo + $3 > 0 THEN 'partial'
        ELSE 'unpaid'
    END,
    updated_at = NOW()
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, student_id, fee_structure_id, amount_kobo, amount_paid_kobo, status, due_date, created_at, updated_at
`

type UpdateStudentFeePaymentParams struct {
	ID             uuid.UUID `json:"id"`
	TenantID       uuid.UUID `json:"tenant_id"`
	AmountPaidKobo int64     `json:"amount_paid_kobo"`
}

func (q *Queries) UpdateStudentFeePayment(ctx context.Context, arg UpdateStudentFeePaymentParams) (StudentFee, error) {
	row := q.db.QueryRow(ctx, updateStudentFeePayment, arg.ID, arg.TenantID, arg.AmountPaidKobo)
	var i StudentFee
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.StudentID,
		&i.FeeStructureID,
		&i.AmountKobo,
		&i.AmountPaidKobo,
		&i.Status,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
