// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: inventory.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createInventoryCategory = `-- name: CreateInventoryCategory :one
INSERT INTO inventory_categories (tenant_id, name)
VALUES ($1, $2)
RETURNING id, tenant_id, name, created_at, updated_at
`

type CreateInventoryCategoryParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Name     string    `json:"name"`
}

func (q *Queries) CreateInventoryCategory(ctx context.Context, arg CreateInventoryCategoryParams) (InventoryCategory, error) {
	row := q.db.QueryRow(ctx, createInventoryCategory, arg.TenantID, arg.Name)
	var i InventoryCategory
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createInventoryItem = `-- name: CreateInventoryItem :one
INSERT INTO inventory_items(
    tenant_id, category_id, name, code, description,
    unit, quantity_in_stock, reorder_level, unit_cost_kobo
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, tenant_id, category_id, name, code, description, unit, quantity_in_stock, reorder_level, unit_cost_kobo, created_at, updated_at
`

type CreateInventoryItemParams struct {
	TenantID        uuid.UUID  `json:"tenant_id"`
	CategoryID      *uuid.UUID `json:"category_id"`
	Name            string     `json:"name"`
	Code            *string    `json:"code"`
	Description     *string    `json:"description"`
	Unit            string     `json:"unit"`
	QuantityInStock int32      `json:"quantity_in_stock"`
	ReorderLevel    int32      `json:"reorder_level"`
	UnitCostKobo    *int64     `json:"unit_cost_kobo"`
}

func (q *Queries) CreateInventoryItem(ctx context.Context, arg CreateInventoryItemParams) (InventoryItem, error) {
	row := q.db.QueryRow(ctx, createInventoryItem,
		arg.TenantID,
		arg.CategoryID,
		arg.Name,
		arg.Code,
		arg.Description,
		arg.Unit,
		arg.QuantityInStock,
		arg.ReorderLevel,
		arg.UnitCostKobo,
	)
	var i InventoryItem
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CategoryID,
		&i.Name,
		&i.Code,
		&i.Description,
		&i.Unit,
		&i.QuantityInStock,
		&i.ReorderLevel,
		&i.UnitCostKobo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInventoryItemByID = `-- name: GetInventoryItemByID :one
SELECT id, tenant_id, category_id, name, code, description, unit, quantity_in_stock, reorder_level, unit_cost_kobo, created_at, updated_at FROM inventory_items
WHERE id = $1 AND tenant_id = $2
`

type GetInventoryItemByIDParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetInventoryItemByID(ctx context.Context, arg GetInventoryItemByIDParams) (InventoryItem, error) {
	row := q.db.QueryRow(ctx, getInventoryItemByID, arg.ID, arg.TenantID)
	var i InventoryItem
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CategoryID,
		&i.Name,
		&i.Code,
		&i.Description,
		&i.Unit,
		&i.QuantityInStock,
		&i.ReorderLevel,
		&i.UnitCostKobo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listInventoryCategories = `-- name: ListInventoryCategories :many
SELECT id, tenant_id, name, created_at, updated_at FROM inventory_categories
WHERE tenant_id = $1
ORDER BY name
`

func (q *Queries) ListInventoryCategories(ctx context.Context, tenantID uuid.UUID) ([]InventoryCategory, error) {
	rows, err := q.db.Query(ctx, listInventoryCategories, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InventoryCategory{}
	for rows.Next() {
		var i InventoryCategory
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInventoryItems = `-- name: ListInventoryItems :many
SELECT i.id, i.tenant_id, i.category_id, i.name, i.code, i.description, i.unit, i.quantity_in_stock, i.reorder_level, i.unit_cost_kobo, i.created_at, i.updated_at, c.name AS category_name
FROM inventory_items i
JOIN inventory_categories c ON c.id = i.category_id
WHERE i.tenant_id = $1
ORDER BY i.name
`

type ListInventoryItemsRow struct {
	ID              uuid.UUID          `json:"id"`
	TenantID        uuid.UUID          `json:"tenant_id"`
	CategoryID      *uuid.UUID         `json:"category_id"`
	Name            string             `json:"name"`
	Code            *string            `json:"code"`
	Description     *string            `json:"description"`
	Unit            string             `json:"unit"`
	QuantityInStock int32              `json:"quantity_in_stock"`
	ReorderLevel    int32              `json:"reorder_level"`
	UnitCostKobo    *int64             `json:"unit_cost_kobo"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	CategoryName    string             `json:"category_name"`
}

func (q *Queries) ListInventoryItems(ctx context.Context, tenantID uuid.UUID) ([]ListInventoryItemsRow, error) {
	rows, err := q.db.Query(ctx, listInventoryItems, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInventoryItemsRow{}
	for rows.Next() {
		var i ListInventoryItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CategoryID,
			&i.Name,
			&i.Code,
			&i.Description,
			&i.Unit,
			&i.QuantityInStock,
			&i.ReorderLevel,
			&i.UnitCostKobo,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CategoryName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
