// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scores.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const getScoresByClassArmAndSubject = `-- name: GetScoresByClassArmAndSubject :many
SELECT s.id, s.tenant_id, s.student_id, s.subject_id, s.assessment_type_id, s.class_arm_id, s.academic_session_id, s.score, s.recorded_by, s.created_at, s.updated_at, st.first_name, st.last_name, st.admission_number
FROM scores s
JOIN students st ON st.id = s.student_id
WHERE s.tenant_id = $1
  AND s.class_arm_id = $2
  AND s.subject_id = $3
  AND s.assessment_type_id = $4
  AND s.academic_session_id = $5
ORDER BY st.last_name, st.first_name
`

type GetScoresByClassArmAndSubjectParams struct {
	TenantID          uuid.UUID `json:"tenant_id"`
	ClassArmID        uuid.UUID `json:"class_arm_id"`
	SubjectID         uuid.UUID `json:"subject_id"`
	AssessmentTypeID  uuid.UUID `json:"assessment_type_id"`
	AcademicSessionID uuid.UUID `json:"academic_session_id"`
}

type GetScoresByClassArmAndSubjectRow struct {
	ID                uuid.UUID          `json:"id"`
	TenantID          uuid.UUID          `json:"tenant_id"`
	StudentID         uuid.UUID          `json:"student_id"`
	SubjectID         uuid.UUID          `json:"subject_id"`
	AssessmentTypeID  uuid.UUID          `json:"assessment_type_id"`
	ClassArmID        uuid.UUID          `json:"class_arm_id"`
	AcademicSessionID uuid.UUID          `json:"academic_session_id"`
	Score             decimal.Decimal    `json:"score"`
	RecordedBy        *uuid.UUID         `json:"recorded_by"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	FirstName         string             `json:"first_name"`
	LastName          string             `json:"last_name"`
	AdmissionNumber   string             `json:"admission_number"`
}

func (q *Queries) GetScoresByClassArmAndSubject(ctx context.Context, arg GetScoresByClassArmAndSubjectParams) ([]GetScoresByClassArmAndSubjectRow, error) {
	rows, err := q.db.Query(ctx, getScoresByClassArmAndSubject,
		arg.TenantID,
		arg.ClassArmID,
		arg.SubjectID,
		arg.AssessmentTypeID,
		arg.AcademicSessionID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetScoresByClassArmAndSubjectRow{}
	for rows.Next() {
		var i GetScoresByClassArmAndSubjectRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.StudentID,
			&i.SubjectID,
			&i.AssessmentTypeID,
			&i.ClassArmID,
			&i.AcademicSessionID,
			&i.Score,
			&i.RecordedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FirstName,
			&i.LastName,
			&i.AdmissionNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getScoresByStudent = `-- name: GetScoresByStudent :many
SELECT s.id, s.tenant_id, s.student_id, s.subject_id, s.assessment_type_id, s.class_arm_id, s.academic_session_id, s.score, s.recorded_by, s.created_at, s.updated_at, at.name AS assessment_name, sub.name AS subject_name
FROM scores s
JOIN assessment_types at ON at.id = s.assessment_type_id
JOIN subjects sub ON sub.id = s.subject_id
WHERE s.tenant_id = $1 AND s.student_id = $2 AND s.academic_session_id = $3
ORDER BY sub.name, at.name
`

type GetScoresByStudentParams struct {
	TenantID          uuid.UUID `json:"tenant_id"`
	StudentID         uuid.UUID `json:"student_id"`
	AcademicSessionID uuid.UUID `json:"academic_session_id"`
}

type GetScoresByStudentRow struct {
	ID                uuid.UUID          `json:"id"`
	TenantID          uuid.UUID          `json:"tenant_id"`
	StudentID         uuid.UUID          `json:"student_id"`
	SubjectID         uuid.UUID          `json:"subject_id"`
	AssessmentTypeID  uuid.UUID          `json:"assessment_type_id"`
	ClassArmID        uuid.UUID          `json:"class_arm_id"`
	AcademicSessionID uuid.UUID          `json:"academic_session_id"`
	Score             decimal.Decimal    `json:"score"`
	RecordedBy        *uuid.UUID         `json:"recorded_by"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	AssessmentName    string             `json:"assessment_name"`
	SubjectName       string             `json:"subject_name"`
}

func (q *Queries) GetScoresByStudent(ctx context.Context, arg GetScoresByStudentParams) ([]GetScoresByStudentRow, error) {
	rows, err := q.db.Query(ctx, getScoresByStudent, arg.TenantID, arg.StudentID, arg.AcademicSessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetScoresByStudentRow{}
	for rows.Next() {
		var i GetScoresByStudentRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.StudentID,
			&i.SubjectID,
			&i.AssessmentTypeID,
			&i.ClassArmID,
			&i.AcademicSessionID,
			&i.Score,
			&i.RecordedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AssessmentName,
			&i.SubjectName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertScore = `-- name: UpsertScore :one
INSERT INTO scores(
    tenant_id, student_id, subject_id,
    assessment_type_id, class_arm_id, academic_session_id,
    score, recorded_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
ON CONFLICT (tenant_id, student_id, subject_id, assessment_type_id, academic_session_id)
DO UPDATE SET
    score = EXCLUDED.score,
    recorded_by = EXCLUDED.recorded_by,
    updated_at = NOW()
RETURNING id, tenant_id, student_id, subject_id, assessment_type_id, class_arm_id, academic_session_id, score, recorded_by, created_at, updated_at
`

type UpsertScoreParams struct {
	TenantID          uuid.UUID       `json:"tenant_id"`
	StudentID         uuid.UUID       `json:"student_id"`
	SubjectID         uuid.UUID       `json:"subject_id"`
	AssessmentTypeID  uuid.UUID       `json:"assessment_type_id"`
	ClassArmID        uuid.UUID       `json:"class_arm_id"`
	AcademicSessionID uuid.UUID       `json:"academic_session_id"`
	Score             decimal.Decimal `json:"score"`
	RecordedBy        *uuid.UUID      `json:"recorded_by"`
}

func (q *Queries) UpsertScore(ctx context.Context, arg UpsertScoreParams) (Score, error) {
	row := q.db.QueryRow(ctx, upsertScore,
		arg.TenantID,
		arg.StudentID,
		arg.SubjectID,
		arg.AssessmentTypeID,
		arg.ClassArmID,
		arg.AcademicSessionID,
		arg.Score,
		arg.RecordedBy,
	)
	var i Score
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.StudentID,
		&i.SubjectID,
		&i.AssessmentTypeID,
		&i.ClassArmID,
		&i.AcademicSessionID,
		&i.Score,
		&i.RecordedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
