// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: students.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createParent = `-- name: CreateParent :one
INSERT INTO parents(
    tenant_id, first_name, last_name,
    email, phone_number, address
)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, tenant_id, first_name, last_name, email, phone_number, address, created_at, updated_at
`

type CreateParentParams struct {
	TenantID    pgtype.UUID `json:"tenant_id"`
	FirstName   string      `json:"first_name"`
	LastName    string      `json:"last_name"`
	Email       *string     `json:"email"`
	PhoneNumber string      `json:"phone_number"`
	Address     *string     `json:"address"`
}

func (q *Queries) CreateParent(ctx context.Context, arg CreateParentParams) (Parent, error) {
	row := q.db.QueryRow(ctx, createParent,
		arg.TenantID,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.PhoneNumber,
		arg.Address,
	)
	var i Parent
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.PhoneNumber,
		&i.Address,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createStudent = `-- name: CreateStudent :one
INSERT INTO students(
    tenant_id, admission_number,
    first_name, last_name, middle_name,
    gender, date_of_birth, status,
    current_class_arm_id, admission_session_id
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, tenant_id, admission_number, first_name, last_name, middle_name, gender, date_of_birth, status, current_class_arm_id, admission_session_id, created_at, updated_at
`

type CreateStudentParams struct {
	TenantID           pgtype.UUID `json:"tenant_id"`
	AdmissionNumber    string      `json:"admission_number"`
	FirstName          string      `json:"first_name"`
	LastName           string      `json:"last_name"`
	MiddleName         *string     `json:"middle_name"`
	Gender             string      `json:"gender"`
	DateOfBirth        pgtype.Date `json:"date_of_birth"`
	Status             string      `json:"status"`
	CurrentClassArmID  pgtype.UUID `json:"current_class_arm_id"`
	AdmissionSessionID pgtype.UUID `json:"admission_session_id"`
}

func (q *Queries) CreateStudent(ctx context.Context, arg CreateStudentParams) (Student, error) {
	row := q.db.QueryRow(ctx, createStudent,
		arg.TenantID,
		arg.AdmissionNumber,
		arg.FirstName,
		arg.LastName,
		arg.MiddleName,
		arg.Gender,
		arg.DateOfBirth,
		arg.Status,
		arg.CurrentClassArmID,
		arg.AdmissionSessionID,
	)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AdmissionNumber,
		&i.FirstName,
		&i.LastName,
		&i.MiddleName,
		&i.Gender,
		&i.DateOfBirth,
		&i.Status,
		&i.CurrentClassArmID,
		&i.AdmissionSessionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getParentById = `-- name: GetParentById :one
SELECT id, tenant_id, first_name, last_name, email, phone_number, address, created_at, updated_at FROM parents
WHERE id = $1 AND tenant_id = $2
`

type GetParentByIdParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) GetParentById(ctx context.Context, arg GetParentByIdParams) (Parent, error) {
	row := q.db.QueryRow(ctx, getParentById, arg.ID, arg.TenantID)
	var i Parent
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.PhoneNumber,
		&i.Address,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getParentsByStudent = `-- name: GetParentsByStudent :many
SELECT p.id, p.tenant_id, p.first_name, p.last_name, p.email, p.phone_number, p.address, p.created_at, p.updated_at, sp.relationship, sp.is_primary FROM parents p
INNER JOIN student_parents sp ON sp.parent_id = p.id
WHERE sp.student_id = $1 AND p.tenant_id = $2
`

type GetParentsByStudentParams struct {
	StudentID pgtype.UUID `json:"student_id"`
	TenantID  pgtype.UUID `json:"tenant_id"`
}

type GetParentsByStudentRow struct {
	ID           pgtype.UUID        `json:"id"`
	TenantID     pgtype.UUID        `json:"tenant_id"`
	FirstName    string             `json:"first_name"`
	LastName     string             `json:"last_name"`
	Email        *string            `json:"email"`
	PhoneNumber  string             `json:"phone_number"`
	Address      *string            `json:"address"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	Relationship string             `json:"relationship"`
	IsPrimary    bool               `json:"is_primary"`
}

func (q *Queries) GetParentsByStudent(ctx context.Context, arg GetParentsByStudentParams) ([]GetParentsByStudentRow, error) {
	rows, err := q.db.Query(ctx, getParentsByStudent, arg.StudentID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetParentsByStudentRow{}
	for rows.Next() {
		var i GetParentsByStudentRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.PhoneNumber,
			&i.Address,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Relationship,
			&i.IsPrimary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStudentByID = `-- name: GetStudentByID :one
SELECT id, tenant_id, admission_number, first_name, last_name, middle_name, gender, date_of_birth, status, current_class_arm_id, admission_session_id, created_at, updated_at FROM students
WHERE id = $1 AND tenant_id = $2
`

type GetStudentByIDParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) GetStudentByID(ctx context.Context, arg GetStudentByIDParams) (Student, error) {
	row := q.db.QueryRow(ctx, getStudentByID, arg.ID, arg.TenantID)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AdmissionNumber,
		&i.FirstName,
		&i.LastName,
		&i.MiddleName,
		&i.Gender,
		&i.DateOfBirth,
		&i.Status,
		&i.CurrentClassArmID,
		&i.AdmissionSessionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStudentById = `-- name: GetStudentById :one
SELECT s.id, s.tenant_id, s.admission_number, s.first_name, s.last_name, s.middle_name, s.gender, s.date_of_birth, s.status, s.current_class_arm_id, s.admission_session_id, s.created_at, s.updated_at, 
    c.name as class_name,
    ca.name as class_arm_name,
    sess.name as admission_session_name
FROM students s
LEFT JOIN class_arms ca ON ca.id = s.current_class_arm_id
LEFT JOIN classes c ON c.id = ca.class_id
LEFT JOIN academic_sessions sess ON sess.id = s.academic_session_id
WHERE s.id = $1 AND s.tenant_id = $2
`

type GetStudentByIdParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

type GetStudentByIdRow struct {
	ID                   pgtype.UUID        `json:"id"`
	TenantID             pgtype.UUID        `json:"tenant_id"`
	AdmissionNumber      string             `json:"admission_number"`
	FirstName            string             `json:"first_name"`
	LastName             string             `json:"last_name"`
	MiddleName           *string            `json:"middle_name"`
	Gender               string             `json:"gender"`
	DateOfBirth          pgtype.Date        `json:"date_of_birth"`
	Status               string             `json:"status"`
	CurrentClassArmID    pgtype.UUID        `json:"current_class_arm_id"`
	AdmissionSessionID   pgtype.UUID        `json:"admission_session_id"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	ClassName            *string            `json:"class_name"`
	ClassArmName         *string            `json:"class_arm_name"`
	AdmissionSessionName *string            `json:"admission_session_name"`
}

func (q *Queries) GetStudentById(ctx context.Context, arg GetStudentByIdParams) (GetStudentByIdRow, error) {
	row := q.db.QueryRow(ctx, getStudentById, arg.ID, arg.TenantID)
	var i GetStudentByIdRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AdmissionNumber,
		&i.FirstName,
		&i.LastName,
		&i.MiddleName,
		&i.Gender,
		&i.DateOfBirth,
		&i.Status,
		&i.CurrentClassArmID,
		&i.AdmissionSessionID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClassName,
		&i.ClassArmName,
		&i.AdmissionSessionName,
	)
	return i, err
}

const getStudentsByParent = `-- name: GetStudentsByParent :many
SELECT s.id, s.tenant_id, s.admission_number, s.first_name, s.last_name, s.middle_name, s.gender, s.date_of_birth, s.status, s.current_class_arm_id, s.admission_session_id, s.created_at, s.updated_at , sp.relationship, sp.is_primary FROM students s
INNER JOIN student_parents sp ON sp.student_id = s.id
WHERE sp.parent_id = $1 AND s.tenant_id = $2
`

type GetStudentsByParentParams struct {
	ParentID pgtype.UUID `json:"parent_id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

type GetStudentsByParentRow struct {
	ID                 pgtype.UUID        `json:"id"`
	TenantID           pgtype.UUID        `json:"tenant_id"`
	AdmissionNumber    string             `json:"admission_number"`
	FirstName          string             `json:"first_name"`
	LastName           string             `json:"last_name"`
	MiddleName         *string            `json:"middle_name"`
	Gender             string             `json:"gender"`
	DateOfBirth        pgtype.Date        `json:"date_of_birth"`
	Status             string             `json:"status"`
	CurrentClassArmID  pgtype.UUID        `json:"current_class_arm_id"`
	AdmissionSessionID pgtype.UUID        `json:"admission_session_id"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	Relationship       string             `json:"relationship"`
	IsPrimary          bool               `json:"is_primary"`
}

func (q *Queries) GetStudentsByParent(ctx context.Context, arg GetStudentsByParentParams) ([]GetStudentsByParentRow, error) {
	rows, err := q.db.Query(ctx, getStudentsByParent, arg.ParentID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetStudentsByParentRow{}
	for rows.Next() {
		var i GetStudentsByParentRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.AdmissionNumber,
			&i.FirstName,
			&i.LastName,
			&i.MiddleName,
			&i.Gender,
			&i.DateOfBirth,
			&i.Status,
			&i.CurrentClassArmID,
			&i.AdmissionSessionID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Relationship,
			&i.IsPrimary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const linkStudentParent = `-- name: LinkStudentParent :exec
INSERT INTO student_parents(
    student_id, parent_id, relationship,
    is_primary
)
VALUES ($1, $2, $3, $4)
ON CONFLICT DO NOTHING
`

type LinkStudentParentParams struct {
	StudentID    pgtype.UUID `json:"student_id"`
	ParentID     pgtype.UUID `json:"parent_id"`
	Relationship string      `json:"relationship"`
	IsPrimary    bool        `json:"is_primary"`
}

func (q *Queries) LinkStudentParent(ctx context.Context, arg LinkStudentParentParams) error {
	_, err := q.db.Exec(ctx, linkStudentParent,
		arg.StudentID,
		arg.ParentID,
		arg.Relationship,
		arg.IsPrimary,
	)
	return err
}

const listStudents = `-- name: ListStudents :many
SELECT id, tenant_id, admission_number, first_name, last_name, middle_name, gender, date_of_birth, status, current_class_arm_id, admission_session_id, created_at, updated_at FROM students
WHERE tenant_id = $1
ORDER BY last_name, first_name
`

func (q *Queries) ListStudents(ctx context.Context, tenantID pgtype.UUID) ([]Student, error) {
	rows, err := q.db.Query(ctx, listStudents, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Student{}
	for rows.Next() {
		var i Student
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.AdmissionNumber,
			&i.FirstName,
			&i.LastName,
			&i.MiddleName,
			&i.Gender,
			&i.DateOfBirth,
			&i.Status,
			&i.CurrentClassArmID,
			&i.AdmissionSessionID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchStudents = `-- name: SearchStudents :many
SELECT id, tenant_id, admission_number, first_name, last_name, middle_name, gender, date_of_birth, status, current_class_arm_id, admission_session_id, created_at, updated_at FROM students
WHERE tenant_id = $1
    AND (
        $2::text IS NULL OR
        first_name ILIKE '%' || $2 || '%' OR 
        last_name ILIKE '%' || $2 || '%' OR
        admission_number ILIKE '%' || $2 || '%'
    )
    AND ($3::uuid IS NULL OR current_class_arm_id = $3)
    AND ($4::text IS NULL OR status = $4)
ORDER BY last_name, first_name
`

type SearchStudentsParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Column2  string      `json:"column_2"`
	Column3  pgtype.UUID `json:"column_3"`
	Column4  string      `json:"column_4"`
}

func (q *Queries) SearchStudents(ctx context.Context, arg SearchStudentsParams) ([]Student, error) {
	rows, err := q.db.Query(ctx, searchStudents,
		arg.TenantID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Student{}
	for rows.Next() {
		var i Student
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.AdmissionNumber,
			&i.FirstName,
			&i.LastName,
			&i.MiddleName,
			&i.Gender,
			&i.DateOfBirth,
			&i.Status,
			&i.CurrentClassArmID,
			&i.AdmissionSessionID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStudent = `-- name: UpdateStudent :one
UPDATE students
SET 
    first_name = COALESCE($3, first_name),
    last_name = COALESCE($4, last_name),
    middle_name = COALESCE($5, middle_name),
    gender = COALESCE($6, gender),
    date_of_birth = COALESCE($7, date_of_birth),
    current_class_arm_id = COALESCE($8, current_class_arm_id),
    status = COALESCE($9, status),
    updated_at = NOW()
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, admission_number, first_name, last_name, middle_name, gender, date_of_birth, status, current_class_arm_id, admission_session_id, created_at, updated_at
`

type UpdateStudentParams struct {
	ID                pgtype.UUID `json:"id"`
	TenantID          pgtype.UUID `json:"tenant_id"`
	FirstName         string      `json:"first_name"`
	LastName          string      `json:"last_name"`
	MiddleName        *string     `json:"middle_name"`
	Gender            string      `json:"gender"`
	DateOfBirth       pgtype.Date `json:"date_of_birth"`
	CurrentClassArmID pgtype.UUID `json:"current_class_arm_id"`
	Status            string      `json:"status"`
}

func (q *Queries) UpdateStudent(ctx context.Context, arg UpdateStudentParams) (Student, error) {
	row := q.db.QueryRow(ctx, updateStudent,
		arg.ID,
		arg.TenantID,
		arg.FirstName,
		arg.LastName,
		arg.MiddleName,
		arg.Gender,
		arg.DateOfBirth,
		arg.CurrentClassArmID,
		arg.Status,
	)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AdmissionNumber,
		&i.FirstName,
		&i.LastName,
		&i.MiddleName,
		&i.Gender,
		&i.DateOfBirth,
		&i.Status,
		&i.CurrentClassArmID,
		&i.AdmissionSessionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
