// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: subjects.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const addSubjectToClass = `-- name: AddSubjectToClass :one
INSERT INTO class_subjects (tenant_id, class_id, subject_id)
VALUES ($1, $2, $3)
RETURNING id, tenant_id, class_id, subject_id, created_at
`

type AddSubjectToClassParams struct {
	TenantID  uuid.UUID `json:"tenant_id"`
	ClassID   uuid.UUID `json:"class_id"`
	SubjectID uuid.UUID `json:"subject_id"`
}

func (q *Queries) AddSubjectToClass(ctx context.Context, arg AddSubjectToClassParams) (ClassSubject, error) {
	row := q.db.QueryRow(ctx, addSubjectToClass, arg.TenantID, arg.ClassID, arg.SubjectID)
	var i ClassSubject
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ClassID,
		&i.SubjectID,
		&i.CreatedAt,
	)
	return i, err
}

const assignTeacher = `-- name: AssignTeacher :one
INSERT INTO teacher_assignments (
    tenant_id, user_id, subject_id, academic_session_id, class_id, class_arm_id
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, tenant_id, user_id, subject_id, academic_session_id, class_id, class_arm_id, created_at
`

type AssignTeacherParams struct {
	TenantID          uuid.UUID  `json:"tenant_id"`
	UserID            uuid.UUID  `json:"user_id"`
	SubjectID         uuid.UUID  `json:"subject_id"`
	AcademicSessionID uuid.UUID  `json:"academic_session_id"`
	ClassID           uuid.UUID  `json:"class_id"`
	ClassArmID        *uuid.UUID `json:"class_arm_id"`
}

func (q *Queries) AssignTeacher(ctx context.Context, arg AssignTeacherParams) (TeacherAssignment, error) {
	row := q.db.QueryRow(ctx, assignTeacher,
		arg.TenantID,
		arg.UserID,
		arg.SubjectID,
		arg.AcademicSessionID,
		arg.ClassID,
		arg.ClassArmID,
	)
	var i TeacherAssignment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.SubjectID,
		&i.AcademicSessionID,
		&i.ClassID,
		&i.ClassArmID,
		&i.CreatedAt,
	)
	return i, err
}

const createSubject = `-- name: CreateSubject :one
INSERT INTO subjects (tenant_id, name, code)
VALUES ($1,$2,$3)
RETURNING id, tenant_id, name, code, created_at, updated_at
`

type CreateSubjectParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Name     string    `json:"name"`
	Code     string    `json:"code"`
}

func (q *Queries) CreateSubject(ctx context.Context, arg CreateSubjectParams) (Subject, error) {
	row := q.db.QueryRow(ctx, createSubject, arg.TenantID, arg.Name, arg.Code)
	var i Subject
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Code,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSubjects = `-- name: ListSubjects :many
SELECT id, tenant_id, name, code, created_at, updated_at FROM subjects
WHERE tenant_id = $1
ORDER BY name
`

func (q *Queries) ListSubjects(ctx context.Context, tenantID uuid.UUID) ([]Subject, error) {
	rows, err := q.db.Query(ctx, listSubjects, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Subject{}
	for rows.Next() {
		var i Subject
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Code,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubjectsByClass = `-- name: ListSubjectsByClass :many
SELECT s.id, s.tenant_id, s.name, s.code, s.created_at, s.updated_at FROM subjects s
INNER JOIN class_subjects cs ON cs.subject_id = s.id
WHERE cs.tenant_id = $1 AND cs.class_id = $2
ORDER BY s.name
`

type ListSubjectsByClassParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	ClassID  uuid.UUID `json:"class_id"`
}

func (q *Queries) ListSubjectsByClass(ctx context.Context, arg ListSubjectsByClassParams) ([]Subject, error) {
	rows, err := q.db.Query(ctx, listSubjectsByClass, arg.TenantID, arg.ClassID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Subject{}
	for rows.Next() {
		var i Subject
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Code,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeacherAssignments = `-- name: ListTeacherAssignments :many
SELECT id, tenant_id, user_id, subject_id, academic_session_id, class_id, class_arm_id, created_at FROM teacher_assignments
WHERE tenant_id = $1 AND academic_session_id = $2
ORDER BY created_at
`

type ListTeacherAssignmentsParams struct {
	TenantID          uuid.UUID `json:"tenant_id"`
	AcademicSessionID uuid.UUID `json:"academic_session_id"`
}

func (q *Queries) ListTeacherAssignments(ctx context.Context, arg ListTeacherAssignmentsParams) ([]TeacherAssignment, error) {
	rows, err := q.db.Query(ctx, listTeacherAssignments, arg.TenantID, arg.AcademicSessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TeacherAssignment{}
	for rows.Next() {
		var i TeacherAssignment
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.SubjectID,
			&i.AcademicSessionID,
			&i.ClassID,
			&i.ClassArmID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
